## Numpy array and basics 
learn about numpy with amit

In [1]:
import numpy as np

##creating array list

In [24]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array: ", arr_1d)

arr_2d = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 0]])
print("2D Array: ", arr_2d)

arr_3d = np.array([[[1, 2, 3]]])
print("3D Array: ", arr_3d)

arr_multi = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Multidimensional Array: ", arr_multi)
print("Shape of Multidimensional Array: ", arr_multi.shape)

1D Array:  [1 2 3 4 5]
2D Array:  [[1 2 3 4 5]
 [6 7 8 9 0]]
3D Array:  [[[1 2 3]]]
Multidimensional Array:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape of Multidimensional Array:  (2, 2, 2)


### List vs numpy array

In [7]:
py_list = [1, 2, 3]
print("Python List Multiplication: ", py_list * 2)

np_array = np.array([1, 2, 3])

print("Python Array Multiplication: ", np_array * 2)

import time
start = time.time()
py_list = [i * 2 for i in range(100000)]
print("\n List Operation Time: ", time.time() - start)

start = time.time()
np_array = np.arange(100000) * 2
print("\n NumPy Operation Time: ", time.time() - start)

Python List Multiplication:  [1, 2, 3, 1, 2, 3]
Python Array Multiplication:  [2 4 6]

 List Operation Time:  0.00566411018371582

 NumPy Operation Time:  0.0014634132385253906


###creating array from scratch

In [ ]:
zeros = np.zeros((3, 4))
print("Zeros array: \n", zeros)

ones = np.ones((2, 3))
print("Ones array: \n", ones)

full = np.full((2, 2), 7)
print("Full Array: \n", full)

random = np.random.random((2, 3))
print("Random Array: \n", random)

sequence = np.arange(0, 10, 2)
print("Sequence Array: \n", sequence)



Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Array: 
 [[7 7]
 [7 7]]
Random Array: 
 [[0.62603623 0.4870872  0.95195289]
 [0.245589   0.25863629 0.47894807]]
Sequence Array: 
 [0 2 4 6 8]


###Vector, Matrix and Tensor

In [3]:
import numpy as np
vector = np.array([1, 2, 3])
print("Vector: ", vector)

Vector:  [1 2 3]


In [4]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Matrix: ", matrix)

Matrix:  [[1 2 3]
 [4 5 6]]


In [6]:
tensor = np.array([[[1, 2], [3, 4], 
                    [5, 6], [7, 8]]])
print("Tensor: ", tensor)

Tensor:  [[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


###Array Properties

In [8]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Shape", arr.shape)
print("Dimensions: ", arr.ndim)
print("Size: ", arr.size)
print("Datatype: ", arr.dtype)

Shape (2, 3)
Dimensions:  2
Size:  6
Datatype:  int64


###Array Reshaping

In [13]:
arr = np.arange(12)
print("Original Array: ", arr)

reshaped = arr.reshape(3, 4)
print("\n Reshaped Array: ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened Array: ", flattened)

###ravels (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n Raveled Array", raveled)

Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped Array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled Array [ 0  1  2  3  4  5  6  7  8  9 10 11]


###Transpose

In [16]:
transpose = reshaped.T
print("\n Transposed Array", transpose)


 Transposed Array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
