In [2]:
import numpy as np

In [8]:
#How do you create a 1D NumPy array containing numbers from 5 to 15?

arr_1d = np.array([5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
print(arr_1d)

arr_1d = np.arange(5, 16)
print(arr_1d)

[ 5  6  7  8  9 10 11 12 13 14 15]
[ 5  6  7  8  9 10 11 12 13 14 15]


In [9]:
#What will be the shape of this array?

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape of the array is: ", arr.shape)

Shape of the array is:  (2, 3)


In [14]:
# Write a command to create a 3×4 array filled with ones.

array_1s = np.ones((3, 4))
print("Array filled with ones: \n", array_1s)

Array filled with ones: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
#What function will you use to create an array of 10 zeros?

array_0s = np.zeros((2, 5))
print("Zeros Array: ", array_0s)

Zeros Array:  [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
#How do you create a 5×5 array filled with 7?

full = np.full((5,5), 7)
print(full)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [20]:
#If you have an array np.arange(12), how would you reshape it into a 3×4 matrix?

arr = np.arange(12)

reshaped = arr.reshape((3, 4))
print(reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [24]:
#Write a command to create an array with numbers from 0 to 20 with step 2.

arr = np.arange(0, 21, 2)

print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [26]:
#What is the output of this code?

arr = np.ones((2,3))
arr = arr * 5
print(arr)



[[5. 5. 5.]
 [5. 5. 5.]]


In [30]:
#How would you create an array of shape (2,3) filled with random integers between 1 and 10?
arr = np.random.randint(1, 11, size = (2, 3))
print(arr)




[[ 1 10  6]
 [ 8  8  3]]


In [ ]:
string = "amitamitamitamitmita"





    


0
2
1
2
1
0
1


In [ ]:
original_list = list
sorted_list = []
used = [False] * len(original_list)

for _ in range(len(original_list)):
    min_num = None
    min_idx = -1
    for idx in range(len(original_list)):
        if not used[idx]:
            num = original_list[idx]
            if min_num is None or num < min_num:
                min_num = num
                min_idx = idx
    sorted_list.append(min_num)
    used[min_idx] = True

print("Sorted list:", sorted_list)

In [3]:
#Create a 1D array of numbers from 10 to 19. Print the first, last, and third element.
import numpy as np
arr_1d = np.arange(10, 20)
print("First Element ", arr_1d[0],"\nLast Element ", arr_1d[-1], "\nThird Element ", arr_1d[2] )

First Element  10 
Last Element  19 
Third Element  12


In [7]:
#Print the array in reverse order using slicing.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("Array in reverse order", arr[::-1])

Array in reverse order [8 7 6 5 4 3 2 1]


In [17]:
#From an array np.arange(20), extract
# elements from index 5 to 10
# every 2nd element from index 2 to 12
# last 5 elements
array = np.arange(20)
print("Elements from index 5 to 10", array[5:11])
print("Every second element from index 2 to 12",array[2:13:2])
print("Last five elements", array[-5:])

Elements from index 5 to 10 [ 5  6  7  8  9 10]
Every second element from index 2 to 12 [ 2  4  6  8 10 12]
Last five elements [15 16 17 18 19]


In [30]:
#Create a 2D array:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
print("Element in 2nd row, 3rd column", arr[1, 2])
print("Entire first row", arr[0])
print("Entire 2nd column", arr[:, 1])

Element in 2nd row, 3rd column 60
Entire first row [10 20 30]
Entire 2nd column [20 50 80]


In [25]:
# From the above arr, extract:
# The submatrix [[20,30],[50,60]]
# The last two rows
# The first two columns
import numpy as np
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
print("The submatrix\n", arr[0:2, 1:3])
print("Last two rows\n", arr[1:])
print("First two columns\n", arr[:, :2 ] )

The submatrix
 [[20 30]
 [50 60]]
Last two rows
 [[40 50 60]
 [70 80 90]]
First two columns
 [[10 20]
 [40 50]
 [70 80]]


In [14]:
# Create an array of numbers 0–29.
# Extract elements from index 10 to 20.
# Extract every 3rd element from the whole array.
# Extract the first 10 elements in reverse order.
import numpy as np
arr = np.arange(0,30)
print("Elements from index 10 to 20", arr[10:21])
print("Every third element", arr[2::2])
print("First 10 elements in reverse order", arr[9::-1])

Elements from index 10 to 20 [10 11 12 13 14 15 16 17 18 19 20]
Every third element [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28]
First 10 elements in reverse order [9 8 7 6 5 4 3 2 1 0]


In [17]:
# Extract:
# First two rows
# Last two columns
# Middle 2×2 block ([[6,7],[10,11]])
# The last row in reverse order
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
print("First 2 rows\n", arr[0:3])
print("Last two columns\n", arr[0:, 2:])

First 2 rows
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Last two columns
 [[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


In [24]:
# From np.arange(1, 26).reshape(5, 5) (a 5×5 matrix):
# Get the first column.
# Get the last row.
# Get elements from the 2nd to 4th row 
# and 2nd to 4th column (a 3×3 submatrix).
arr = np.arange(1, 26).reshape(5, 5)
print(arr)
print("First Column", arr[0:, 0])
print("Last Row", arr[-1])
print("Elements from 2nd to 4th row and 2nd to 4th column\n", arr[1:4, 1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First Column [ 1  6 11 16 21]
Last Row [21 22 23 24 25]
Elements from 2nd to 4th row and 2nd to 4th column
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]
