NumPy Array Operations 

In [7]:
import numpy as np
arr = np.arange(1, 11)
print("Basic Slicing", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative Indexing", arr[-3])

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative Indexing 8


In [15]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific Element", arr_2d[1, 2])
print("Entire Row", arr_2d[1])
print("Entire Column", arr_2d[:, 1])

Specific Element 6
Entire Row [4 5 6]
Entire Column [2 5 8]


Sorting

In [20]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2])
print("Sorted Array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by row", np.sort(arr_2d_unsorted, axis=0))

Sorted Array [1 1 2 3 4 5 9]
Sorted 2D array by row [[1 1]
 [2 2]
 [3 3]]


Filter Array

In [23]:
numbers = np.arange(1, 11)
even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers", even_numbers)

Even Numbers [ 2  4  6  8 10]


Filter with mask

In [3]:
import numpy as np
numbers = np.arange(1, 11)
mask  = numbers > 5
print("Numbers greater than 5", numbers[mask])

Numbers greater than 5 [ 6  7  8  9 10]


Fancy Indexing Vs np.where

In [6]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("NP Where", numbers[where_result])

[1 3 5]
NP Where [ 6  7  8  9 10]


In [10]:
condition_array = np.where(numbers > 5, numbers * 4, numbers)
print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]


Adding and removing data  

In [14]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


Array Compatibiliy

In [17]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Compatibiliy shapes", a.shape == b.shape)


Compatibiliy shapes True


In [23]:
original = np.array([[1, 2], 
                     [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print("Original Array", original)
print("Array with new row\n", with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("Array with new column\n", with_new_col)

Original Array [[1 2]
 [3 4]]
Array with new row
 [[1 2]
 [3 4]
 [5 6]]
Array with new column
 [[1 2 7]
 [3 4 8]]


In [25]:
arr = np.array([1, 2, 3, 4, 5])
print("Array before deletion", arr)
deleted = np.delete(arr,2)
print("Array after deletion", deleted)

Array before deletion [1 2 3 4 5]
Array after deletion [1 2 4 5]
