NumPy Practice Questions

Create a NumPy array with values from 1 to 50.

In [12]:
import numpy as np
a = np.arange(1, 51)
print("Array from 1 to 50 is: \n", a)

Array from 1 to 50 is: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


Create a 3×3 matrix filled with all 5’s.

In [17]:
b = np.full((3,3), 5)
print("3 X 3 matrix filled \n", b)

3 X 3 matrix filled 
 [[5 5 5]
 [5 5 5]
 [5 5 5]]


Create a NumPy array of even numbers between 10 and 30.

In [22]:
c = np.arange(10, 31, 2)
print("", c)

 [10 12 14 16 18 20 22 24 26 28 30]


Generate an array of 20 random integers between 1 and 100.

In [29]:
d = np.random.randint(1, 101 ,20)
print(d)

[65 47 42 36 92 75 36 54 11 86 99 67 25 14 86 79 32 38 51 56]


Create a 4×4 identity matrix.

In [31]:
e = np.eye(4, 4)
print(e)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Create an array of shape (2,3) filled with random floats between 0 and 1.

In [1]:
import numpy as np
f = np.random.rand(2,3)
print(f)

[[0.84469187 0.52801352 0.65717773]
 [0.29433075 0.87235633 0.47325075]]


Reshape np.arange(1, 25) into a 4×6 matrix.

In [3]:
import numpy as np
g = np.arange(1, 25)
reshaped_g= g.reshape(4, 6)
print(reshaped_g)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


From arr = np.arange(1, 26).reshape(5, 5):
Select the first row
Select the last column
Select the middle 3×3 submatrix

In [22]:
arr = np.arange(1, 26).reshape(5, 5)
print(arr)
print("First Row: ",arr[0])
print("Last Column: ", arr[:, -1])
print("Middle 3 x 3 matrix: ",arr[1:4, 1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First Row:  [1 2 3 4 5]
Last Column:  [ 5 10 15 20 25]
Middle 3 x 3 matrix:  [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


Given arr = np.array([2, 4, 6, 8, 10, 12, 14]), select:
Numbers greater than 8
Every alternate element
Reverse the array

In [ ]:
arr = np.array([2, 4, 6, 8, 10, 12, 14])
numbers_greater_than_8 = np.where(arr > 8)
print("Numbers greater than 8", arr[numbers_greater_than_8])
print("Every alternate element", arr[::2])
print("Reverse the array", arr[::-1])


Numbers greater than 8 [10 12 14]
Every alternate element [ 2  6 10 14]
Reverse the array [14 12 10  8  6  4  2]


Extract only diagonal elements from this 4×4 matrix:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9,10,11,12],
                [13,14,15,16]])

In [5]:
import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
for i, j in np.ndenumerate(arr):
    if i[0] == i[1]:
        print(i,j)

(0, 0) 1
(1, 1) 6
(2, 2) 11
(3, 3) 16


Given arr = np.array([5, 3, 9, 1, 10, 6]):

Sort the array in ascending order

Sort the array in descending order

In [29]:
arr = np.array([5, 3, 9, 1, 10, 6])
print("Sorting in Ascending Order: ", np.sort(arr))
print("Sorting in Descending Order: ", np.sort(arr)[::-1])

Sorting in Ascending Order:  [ 1  3  5  6  9 10]
Sorting in Descending Order:  [10  9  6  5  3  1]


From the 2D array:

arr = np.array([[10, 2, 30],
                [5, 25, 15]])


Sort each row individually

Sort each column individually

In [ ]:
arr = np.array([[10, 2, 30], [5, 25, 15]])