Q1. Iterate through the following 2D array using nditer and print each element.


In [22]:
import numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for element in np.nditer(a):
    print(element)

with_new_row = np.hstack(a)
print(with_new_row)

1
2
3
4
5
6
7
8
[1 2 3 4 5 6 7 8]


Q2. Print indices and values of each element in a 2D array.


In [6]:
b = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 0]])
for element in np.ndenumerate(b):
    print(element)

((0, 0), np.int64(1))
((0, 1), np.int64(2))
((0, 2), np.int64(3))
((0, 3), np.int64(4))
((0, 4), np.int64(5))
((1, 0), np.int64(6))
((1, 1), np.int64(7))
((1, 2), np.int64(8))
((1, 3), np.int64(9))
((1, 4), np.int64(0))


Q3. Find indices of elements greater than 25.


In [11]:
c = np.array([1, 2, 3, 4, 5, 6, 87, 98, 35, 25, 26, 43, 65, 43, 78])

greater_than_25 = np.where(c > 25)
sorted_c = np.sort(c[greater_than_25])
print(sorted_c)

[26 35 43 43 65 78 87 98]


Q4. Sort the array in ascending and descending order.

In [18]:
d = np.array([5, 6, 3, 9, 6, 3, 2, 1, 5, 0, 8, 23, 45, 68])

sorted_in_ascending = np.sort(d)
print("Sorted array in ascending order: \n", sorted_in_ascending)

sorted_in_descending = np.sort(d)[::-1]
print("Sorted in descending order; \n", sorted_in_descending)

Sorted array in ascending order: 
 [ 0  1  2  3  3  5  5  6  6  8  9 23 45 68]
Sorted in descending order; 
 [68 45 23  9  8  6  6  5  5  3  3  2  1  0]


Q5. Sort rows and columns of a 2D array.


In [51]:
import random
e = np.random.randint(10, size = (3, 3))
print("unsorted array: \n" ,e)
sorted_e = np.sort(e)
print("Sorted Array: \n", sorted_e)

unsorted array: 
 [[9 2 1]
 [9 8 3]
 [7 0 3]]
Sorted Array: 
 [[1 2 9]
 [3 8 9]
 [0 3 7]]


Q6. Find the index where value 6 should be inserted in sorted array [1, 3, 5, 7, 9].

In [52]:
f = np.array([1, 3, 5, 7, 9])
check_where_6_be_inserted = np.searchsorted(f, 6)
print("Index where 6 should be inserted to maintain order: ", check_where_6_be_inserted)

Index where 6 should be inserted to maintain order:  3


Q7. Find where to insert 5 using side='left' and side='right'.

In [97]:
i = np.array([[1, 2, 3, 4],
              [6, 7, 8, 9],
              [10, 11, 12, 13]])

reshaped_i = i.reshape(-1)
check_5_insertion = np.searchsorted(reshaped_i, 5, side= "left")
print("Index where 5 should be inserted to maintain order: ", check_5_insertion)


Index where 5 should be inserted to maintain order:  4


Q8. Iterate a 3D array using nditer and print all values in a single line.

In [3]:
import numpy as np 
g = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

for element in np.nditer(g):
    print(element)

1
2
3
4
5
6
7
8
9


Q9. Print only the elements on the diagonal using ndenumerate.


In [98]:
import numpy as np
h = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

for i, j  in np.ndenumerate(h):
    if i[0] == i[1]:
        print( i, j)

(0, 0) 1
(1, 1) 5
(2, 2) 9


Q10. Replace negative numbers with 0 using ndenumerate.

In [118]:
j = np.array([[[1, 2, 3, 4, 5],
               [6, 7, -8, 9, 10],
               [-11, 12, 13, -14, 15],
               [16, -17, 18, 19, 20]]])
reshaped_j = j.reshape(-1)

for i, k in np.ndenumerate(j):
    replace_with_0 = np.where(k < 0, k - k, k)
    print(replace_with_0, end = " ")
    
    
    

1 2 3 4 5 6 7 0 9 10 0 12 13 0 15 16 0 18 19 20 

Q11. Find even numbers and their indices.

In [121]:
k = np.array([[[1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12],
             [13, 14, 15, 16],
             [17, 18, 19, 20]]])

for i, j in np.ndenumerate(k):
    if j % 2 == 0:
        print(i, j)


(0, 0, 1) 2
(0, 0, 3) 4
(0, 1, 1) 6
(0, 1, 3) 8
(0, 2, 1) 10
(0, 2, 3) 12
(0, 3, 1) 14
(0, 3, 3) 16
(0, 4, 1) 18
(0, 4, 3) 20


Q12. Replace all numbers greater than 50 with 100.

In [132]:
l = np.array([[[89, 34, 55, 78],
               [67, 33, 54, 32],
               [45, 12, 51, 17],
               [1, 90, 7, 3]]])

for i, j in np.ndenumerate(l):
    if j > 50:
        j = 100
    print(i, j)

replace_with_100 = np.where(l > 50, 100, l)
print(replace_with_100)

(0, 0, 0) 100
(0, 0, 1) 34
(0, 0, 2) 100
(0, 0, 3) 100
(0, 1, 0) 100
(0, 1, 1) 33
(0, 1, 2) 100
(0, 1, 3) 32
(0, 2, 0) 45
(0, 2, 1) 12
(0, 2, 2) 100
(0, 2, 3) 17
(0, 3, 0) 1
(0, 3, 1) 100
(0, 3, 2) 7
(0, 3, 3) 3
[[[100  34 100 100]
  [100  33 100  32]
  [ 45  12 100  17]
  [  1 100   7   3]]]


Q13. Sort a 2D array column-wise.

In [157]:
m = np.array([[10, 11, 12],
              [7, 8, 9],
              [1, 3, 2],
              [6, 5, 4]
              ])

sorted_m_column_wise = np.sort(m, axis=0)
print(sorted_m_column_wise)

[[ 1  3  2]
 [ 6  5  4]
 [ 7  8  9]
 [10 11 12]]


Q14. Insert multiple values [4, 10] in sorted array [1, 3, 5, 7, 9].

In [198]:
n = np.array([1, 3, 5, 9])
inserted_values = np.insert(n, [2, -1], [4, 10])
print(inserted_values)


[ 1  3  4  5 10  9]


Q15. Insert values [2, 8] into sorted array and actually insert them.

In [ ]:
o = np.array([1, 3, 5, 9])
inserted_value = np.insert(o, len(o) ,[2, 8])
print(inserted_value) 

[1 3 5 9 2 8]
