In [57]:
import numpy as np

# linespace and broadcasting

# Linspace

In [58]:
a = np.linspace(0, 2, 10, retstep=True, endpoint=False)
print(a)

(array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8]), np.float64(0.2))


In [59]:
b = np.eye(2, dtype=int)
print("2 X 2 Identity Matrix: \n", b)

c = np.identity(3, dtype=int)
print("\n3 X 3 Identity Matrix: \n", c)

2 X 2 Identity Matrix: 
 [[1 0]
 [0 1]]

3 X 3 Identity Matrix: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [60]:
d = np.diag([2, 3, 2])
print("Diagonal Matrix: \n", d)

Diagonal Matrix: 
 [[2 0 0]
 [0 3 0]
 [0 0 2]]


In [61]:
e = np.diag((1, 2, 3, 4))
print("Diagonal Matrix : \n", e)

Diagonal Matrix : 
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# Broadcasting describes how numpy treats array with differnt shapes during arithmatic operations.
# It starts with trailing the right most dimensions and works its way left.
# Two dimensions are compatible when they are equal or one of them is one.

In [62]:
a = np.array([10, 20])
b = np.array([5])

addition_of_array = a + b 
print("Addition: ", addition_of_array)

Addition:  [15 25]


In [63]:
# Additon not possible in this case
c = np.ones((3, 2))
d = np.ones((4, 1))

addition = c + d
print(addition)

ValueError: operands could not be broadcast together with shapes (3,2) (4,1) 

In [ ]:
e = np.full((2, 5, 2), 3, dtype=int)
f = np.ones((1, 5, 1), dtype=int)

addition = e + f
print(addition)

# Masking
# It means using a boolean condition to filter or select elements from an array

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a > 4
print(b)
print(a)

[False False False False  True  True]
[-1 -1 -1 -1 -1 -1]


In [116]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a > 4

a[a > 4] = -1
print(a)

filter_elements = (a > 2)  & (a < 5)
print(a[filter_elements])



[ 1  2  3  4 -1 -1]
[3 4]
