In [1]:
import numpy as np

In [5]:
a = np.zeros(5, dtype=int)
print(a)

[0 0 0 0 0]


In [ ]:
b = np.zeros((2, 2), dtype=int)
print(b)

[[0 0]
 [0 0]]


In [13]:
c = np.ones((2, 2, 2), dtype=int)
print(c)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [43]:
d = np.empty((2,2), dtype=int)
print(d)

[[            0 2319120420656]
 [2319120422256 2319120422336]]


arange function is used to create array with evenly spaced values within in a specified range

In [56]:
e = np.arange(1, 11, 2)
print(e)

[1 3 5 7 9]


In [83]:
f = np.arange(1, 21)
print("1D Array: ",f)
reshaped_f = f.reshape((5,4))
print("\n2D Array: \n", reshaped_f)

reshaped_f_into_3d = f.reshape((2, 5, 2))
print("\n3D Array: \n", reshaped_f_into_3d)

1D Array:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

2D Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]

3D Array: 
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


Mathematical Functions


In [98]:
a = np.arange(1, 21).reshape(4, 5)
b = np.arange(21, 41).reshape(4, 5)

addition_of_a_b = np.add(a, b)
print(f"Addition of \n{a} + \n\n{b} = \n\n", addition_of_a_b)


Addition of 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] + 

[[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]] = 

 [[22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]
 [52 54 56 58 60]]


In [100]:
subtraction_of_a_b = np.subtract(a, b)
print(f"\nSubtraction of \n{a} - \n\n{b} = \n\n", subtraction_of_a_b)


Subtraction of 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] - 

[[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]] = 

 [[-20 -20 -20 -20 -20]
 [-20 -20 -20 -20 -20]
 [-20 -20 -20 -20 -20]
 [-20 -20 -20 -20 -20]]


In [102]:
mutliplication_of_a_b = np.multiply(a, b)
print(f"\nMutliplication of \n{a} * \n\n{b} = \n\n",  mutliplication_of_a_b)


Mutliplication of 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] * 

[[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]] = 

 [[ 21  44  69  96 125]
 [156 189 224 261 300]
 [341 384 429 476 525]
 [576 629 684 741 800]]


In [104]:
division_of_a_b = np.multiply(a, b)
print(f"\nDivision of \n{a} / \n\n{b} = \n\n",  division_of_a_b)


Division of 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] / 

[[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]] = 

 [[ 21  44  69  96 125]
 [156 189 224 261 300]
 [341 384 429 476 525]
 [576 629 684 741 800]]


In [142]:
s = np.arange(1, 21).reshape(4, 5)
t = np.arange(21, 41).reshape(5, 4)

dot_product_of_s_t = np.dot(s, t)
print(f"\nDot Product of \n{s} . \n\n{t} = \n\n",  dot_product_of_s_t)


Dot Product of 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] . 

[[21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]
 [33 34 35 36]
 [37 38 39 40]] = 

 [[ 475  490  505  520]
 [1200 1240 1280 1320]
 [1925 1990 2055 2120]
 [2650 2740 2830 2920]]


In [146]:
p = np.arange(21, 41).reshape(5, 4)
print("Largest Element in the Array: ", p.max())
print("Smallest Element in the Array: ", p.min())
print("Index of Lagrest Element in the Array: ", p.argmax())
print("Index of Smallest Element in the Array: ", p.argmin())

Largest Element in the Array:  40
Smallest Element in the Array:  21
Index of Lagrest Element in the Array:  19
Index of Smallest Element in the Array:  0
