NumPy 3D Array

In [1]:
import numpy as np

In [4]:
arr = np.array([[[2, 1, 1],
                 [1, 2, 3],
                 [3, 1, 2],
                 [4, 1, 1],
                 [3, 3, 3]]])
print("MultiDimensional Array: \n", arr)
print("Shape of MultiDimensional Array: \n", arr.shape)

MultiDimensional Array: 
 [[[2 1 1]
  [1 2 3]
  [3 1 2]
  [4 1 1]
  [3 3 3]]]
Shape of MultiDimensional Array: 
 (1, 5, 3)


In [8]:
arr_1 = np.array([[[2], [1], [1]]])
print("arr_1: \n", arr_1)

arr_2 = np.array([[[1], [2], [3]]])
print("arr_2: \n", arr_2)

arr_3 = np.array([[[3], [1], [2]]])
print("arr_3: \n", arr_3)

arr_4 = np.array([[[4], [1], [1]]])
print("arr_4: \n", arr_4)

arr_5 = np.array([[[3], [3], [3]]])
print("arr_5: \n", arr_5)
print("Shape of arr_5: ", arr_5.shape )
print("Dimensions of arr_5: ", arr.ndim)


arr_1: 
 [[[2]
  [1]
  [1]]]
arr_2: 
 [[[1]
  [2]
  [3]]]
arr_3: 
 [[[3]
  [1]
  [2]]]
arr_4: 
 [[[4]
  [1]
  [1]]]
arr_5: 
 [[[3]
  [3]
  [3]]]
Shape of arr_5:  (1, 3, 1)
Dimensions of arr_5:  3


In [14]:
arr_10d = np.array([1, 2, 3], ndmin = 10)
print("10-Dimensional Array: ", arr_10d)
print("Dimensions in 10-D Array: ", arr_10d.ndim)
print("Shape of 10-D Array: ", arr_10d.shape)

10-Dimensional Array:  [[[[[[[[[[1 2 3]]]]]]]]]]
Dimensions in 10-D Array:  10
Shape of 10-D Array:  (1, 1, 1, 1, 1, 1, 1, 1, 1, 3)


Indexing

In [ ]:
#Indexing in 1-D Array
a = np.array([1, 2, 3, 4, 5])
print("Element at index 2: ", a[2])

#Indexing in 2-D Array
b = np.array([[1, 2, 3], [4, 5, 6]])
print("Element at index of second Array first element: ", b[1][0])

#Indexing in 3-D Array
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Element at index of first array inside second Array and their second element:  ", c[1][0][1])

Element at index 2:  3
Element at index of second Array first element:  4
Element at index of first array inside second Array and their second element:   6


Slicing

In [42]:
# a  = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# print(a[2:6:1])

b = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10]])
print("Output 1: \n", b[1][1:4])

array_1d = np.array([b[0][2],b[1][2]])
print("Output 2: \n", array_1d)

array_2d = np.array([b[0][1:4],b[1][1:4]])
print("Output 3: \n", array_2d)

Output 1: 
 [7 8 9]
Output 2: 
 [3 8]
Output 3: 
 [[2 3 4]
 [7 8 9]]
