# Random Function

In [11]:

import random 
import numpy as np
a = np.random.randint(1, 100)
print(a)

56


In [5]:
a = np.random.rand()
print(a)

0.0013146527452125856


In [7]:
b = np.random.rand(2,2)
print(b)

[[0.95630951 0.58418917]
 [0.30513318 0.47561331]]


In [12]:
c = np.random.uniform(1, 100, (2, 2))
print(c)

[[84.24408209 79.77182682]
 [38.27568472 78.76881429]]


In [16]:
a = [10, 20, 30, 40, 50, 60, 70]
d = np.random.choice(a)
print(d)

d = np.random.choice(a, 3)
print(d)

d = np.random.choice(a, (2, 2))
print(d)

20
[20 20 30]
[[20 10]
 [40 30]]


# Joining of array(1d)

In [25]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Concatenate Arrays: \n", np.concatenate((a, b)))
print("\n Horizontal Stack: \n", np.hstack((a, b)))
print("\n Vertical Stack: \n", np.vstack((a, b)))
print("\n Stack:  Rows\n", np.stack((a, b), axis=0))
print("\n Stack: Columns\n", np.stack((a, b), axis=1))

Concatenate Arrays: 
 [1 2 3 4 5 6]

 Horizontal Stack: 
 [1 2 3 4 5 6]

 Vertical Stack: 
 [[1 2 3]
 [4 5 6]]

 Stack:  Rows
 [[1 2 3]
 [4 5 6]]

 Stack: Columns
 [[1 4]
 [2 5]
 [3 6]]


In [40]:
e = np.random.rand(2, 2)
f = np.random.rand(2, 2)
print(e)

print("\nHorizontal Stack: \n", np.hstack((e, f)))
print("\nVertical Stack: \n",np.vstack((e, f)))
print("\n Stack: Rows\n", np.stack((e, f), axis=0))
print("\n Stack: Columns\n", np.stack((e, f), axis=1))

[[0.22132193 0.02899934]
 [0.47597592 0.49411312]]

Horizontal Stack: 
 [[0.22132193 0.02899934 0.74507463 0.37862575]
 [0.47597592 0.49411312 0.59986166 0.86358378]]

Vertical Stack: 
 [[0.22132193 0.02899934]
 [0.47597592 0.49411312]
 [0.74507463 0.37862575]
 [0.59986166 0.86358378]]

 Stack: Rows
 [[[0.22132193 0.02899934]
  [0.47597592 0.49411312]]

 [[0.74507463 0.37862575]
  [0.59986166 0.86358378]]]

 Stack: Columns
 [[[0.22132193 0.02899934]
  [0.74507463 0.37862575]]

 [[0.47597592 0.49411312]
  [0.59986166 0.86358378]]]


# Universal Functions --> unfunc

In [46]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Addition: \n", np.add(a, b))
print("\nSubtraction: \n", np.subtract(a,  b))
print("\nMultiply: \n", np.multiply(a,  b))
print("\nDivision: \n", np.divide(a,  b))
print("\nFloor Division: \n", np.floor(a,  b))
print("\nModulus: \n", np.mod(a, b))
print("\nPower: \n", np.power(a, 2))

Addition: 
 [5 7 9]

Subtraction: 
 [-3 -3 -3]

Multiply: 
 [ 4 10 18]

Division: 
 [0.25 0.4  0.5 ]

Floor Division: 
 [1 2 3]

Modulus: 
 [0 0 0]

Power: 
 [1 4 9]


In [48]:
a = np.sin([0])
print("Sin 0: ", a)
b = np.cos([3])
print("\nCos 3:  ", b)
c = np.tan([60])
print("\nTan 60: ", c)

Sin 0:  [0.]

Cos 3:   [-0.9899925]

Tan 60:  [0.32004039]


In [54]:
a = np.equal([1, 2], [1, 3])
print("Equal: ",a)

b = np.not_equal([1, 2], [1, 3])
print("Not Equal: ",b)

c = np.greater([1, 2], [1, 3])
print("Greater: ", c)

d = np.less([1, 2], [1, 3])
print("Less: ", d)

e = np.greater_equal([1, 2], [1, 3])
print("Greater Equal: ", e)

f = np.less_equal([1, 2], [1, 3])
print("Less Equal: ", f)


Equal:  [ True False]
Not Equal:  [False  True]
Greater:  [False False]
Less:  [False  True]
Greater Equal:  [ True False]
Less Equal:  [ True  True]


# Logical Operators

In [59]:
a = np.logical_and([True, False], [True, False])
print("Logical AND: ", a)

b = np.logical_not([True, False])
print("Logical NOT: ", b)

c = np.logical_or([True, False], [True, False])
print("Logical OR: ", c)

d = np.logical_xor([True, False], [True, False])
print("Logical XOR: ", d)


Logical AND:  [ True False]
Logical NOT:  [False  True]
Logical OR:  [ True False]
Logical XOR:  [False False]


# Squareroot

In [71]:
a = np.sqrt([4, 9])
print("Squareroot", a)

b = np.cbrt([8, 27])
print("Cube Root", b)

c = np.negative([-1, 2])
print("Negative", c)

d = np.abs([-1, -5])
print("Absolute", d)

e = np.maximum([1, 2],[3,4])
print("Maximum", e)

f = np.minimum([4, 9],[1,2])
print("Minimum", f)

g = np.round([1, 2, 4, 7])
print("Round", g)


Squareroot [2. 3.]
Cube Root [2. 3.]
Negative [ 1 -2]
Absolute [1 5]
Maximum [3 4]
Minimum [1 2]
Round [1 2 4 7]
