 Create a 1D array of size 5 using:
 np.empty()
 np.zeros()
 np.ones()
 Compare the outputs.


In [39]:
import numpy as np
a = np.empty((5), dtype=int)
print("Empty Array: ", a)

b = np.zeros((5), dtype=int)
print("Array of Zero: ", b)

c = np.ones((5), dtype=int)
print("Array of ones: ", c)


Empty Array:  [25895968444448860 23925768161198147 32370111954616435     2068546912256
                 0]
Array of Zero:  [0 0 0 0 0]
Array of ones:  [1 1 1 1 1]


Create a 2D array (3×3) with np.empty(). What do you notice about the values?


In [41]:
arr_2d = np.empty((3, 3), dtype=int)
print("2D Array using empty: ", arr_2d)

2D Array using empty:  [[0 0 0]
 [0 0 0]
 [0 0 0]]


Create a 2D array (2×4) with np.zeros(dtype=int).

In [45]:
arr2d = np.zeros((2, 4), dtype=int)
print("2D arrays with zeros: \n", arr2d)
print("Dimensions of Array: ", arr2d.ndim)

2D arrays with zeros: 
 [[0 0 0 0]
 [0 0 0 0]]
Dimensions of Array:  2


Create a 3D array (2×2×3) filled with ones (np.ones).

In [49]:
arr_3d = np.ones((2, 2, 3), dtype=int)
print("3D Array filled with Ones: ", arr_3d)
print("Dimensions of Array: ", arr_3d.ndim)

3D Array filled with Ones:  [[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
Dimensions of Array:  3


Create a 2×3 float array using np.empty(), then fill it with 7.

In [ ]:
ar_2d = np.empty((2, 3), dtype=float)
ar_2d.fill(7)
print("2D Array filled with 7: ", ar_2d)

2D Array filled with 7:  [[7. 7. 7.]
 [7. 7. 7.]]


Create a 1D array of 6 elements filled with zeros, then change the middle two elements to 5.

In [61]:
arr_1d = np.zeros(6, dtype=int)
arr_1d[2:4] = 5
print("With middle two element 5: ", arr_1d)


With middle two element 5:  [0 0 5 5 0 0]


Create a 2×2 array using np.ones() and multiply it by 10.

In [64]:
array_2d = np.ones((2, 2), dtype=int)
new_arr = array_2d * 10
print(new_arr)

[[10 10]
 [10 10]]


 Create a 4×4 empty array and check its dtype. Then create the same with dtype=int.

In [68]:
arr_4d = np.empty((4, 4))
print("4D Array: \n", arr_4d, "\nDatatype of the array: ", arr_4d.dtype)

int_arr = arr_4d.astype(int)
print("Changing the dataype of the array: ", int_arr.dtype)

4D Array: 
 [[6.23042070e-307 4.67296746e-307 1.69121096e-306 9.79101761e-307]
 [8.34441742e-308 1.78022342e-306 6.23058028e-307 9.79107872e-307]
 [6.89807188e-307 7.56594375e-307 6.23060065e-307 1.78021527e-306]
 [8.34454050e-308 1.11261027e-306 1.15706896e-306 1.33512173e-306]] 
Datatype of the array:  float64
Changing the dataype of the array:  int64


Create a 2×5 array using np.zeros(), then add 1 to every element

In [71]:
arr = np.zeros((2, 5), dtype=int)
arr.fill(1)
print("Adding 1 in place of zero in the array: \n", arr)

Adding 1 in place of zero in the array: 
 [[1 1 1 1 1]
 [1 1 1 1 1]]


Create an array of shape (3, 2) with np.ones(dtype=bool). What values do you get?

In [74]:
array = np.ones((3, 2), dtype=bool)
print("Array after changing the datatype to boolean: \n", array)


Array after changing the datatype to boolean: 
 [[ True  True]
 [ True  True]
 [ True  True]]
