Questions

In [3]:
# 1. [10, 20, 30, 40, 50, 60, 70, 80]
# Slice elements from index 2 to 5.
import numpy as np
arr = np.array([10, 20, 30 , 40, 50, 60, 70, 80])
print("Elements from index 2 to 5", arr[2:6])

Elements from index 2 to 5 [30 40 50 60]


In [8]:
# 2. [[5, 10, 15, 20],
#  [25, 30, 35, 40],
#  [45, 50, 55, 60],
#  [65, 70, 75, 80]]
# Extract the second and third rows

arr = np.array([[5, 10, 15, 20],
                [25, 30, 35, 40],
                [45, 50, 55, 60],
                [65, 70, 75, 80]])

print("Second and Third row\n", arr[1:3])

# 3. From the same array, extract the last 2 columns from all rows.
print("Last 2 columns\n", arr[:, -2:])

Second and Third row
 [[25 30 35 40]
 [45 50 55 60]]
Last 2 columns
 [[15 20]
 [35 40]
 [55 60]
 [75 80]]


In [13]:
# 4. arr = np.array([100, 200, 300, 400, 500, 600])
# Slice the array to get every second element.

arr = np.array([100, 200, 300, 400, 500, 600])
print("Every Second Element\n", arr[1::2])

Every Second Element
 [200 400 600]


In [82]:
# Create a 3D Array 
# QUESTIONS 
# 1. Extract the first block (i.e., the first 2D array).
# 2. Extract the second row from the second block.
# 3. Extract the second column across all blocks and rows.
# 4. Extract the element "9" using indexing.
# 5. Extract the last row from each block.
# 6. Extract the last element from each row of each block.
# 7. Extract all elements greater than 5.

arr_3d = np.array([[[1, 2, 3],
                 [4, 5, 6]],
                 [[7, 8, 9],
                  [10, 11, 12]]
                 ])
print(arr_3d.shape)

print("First block\n", arr_3d[0])
print("Second row from the second block\n", arr_3d[1,1])
print("Second column across all blocks and rows\n", arr_3d[:, :, 1])
print("Element 9 using indexing\n", arr_3d[1, 0, 2])
print("Last row from each block\n", arr_3d[:, 1])
print("Last element from each row of each block\n", arr_3d[:, :, -1] )
greater_than_5 = arr_3d>5
print("All elements greater than 5\n", arr_3d[greater_than_5])




(2, 2, 3)
First block
 [[1 2 3]
 [4 5 6]]
Second row from the second block
 [10 11 12]
Second column across all blocks and rows
 [[ 2  5]
 [ 8 11]]
Element 9 using indexing
 9
Last row from each block
 [[ 4  5  6]
 [10 11 12]]
Last element from each row of each block
 [[ 3  6]
 [ 9 12]]
All elements greater than 5
 [ 6  7  8  9 10 11 12]


In [59]:
# Create a 1D array: [10, 20, 30, 40, 50, 60, 70, 80].
# a) Slice elements from index 2 to 5.
# b) Get every second element.
# c) Reverse the array.

array = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print("Slice elements from index 2 to 5", array[3:6])
print("Every second element",array[1:6:2])
print("Reverse the array", array[::-1])


Slice elements from index 2 to 5 [40 50 60]
Every second element [20 40 60]
Reverse the array [80 70 60 50 40 30 20 10]


In [80]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])
b=np.where(a>40)
print(a[b])

[50 60 70 80]


In [2]:
# # Create a 2d Array
# Extract the second and third rows.
# Get the first two columns.
# Slice the submatrix [[30, 35], [50, 55]].
# Get all elements of the last row in reverse order.
import numpy as np
array2d = np.array([
        [5, 10, 15, 20],
        [25, 30, 35, 40],
        [45, 50, 55, 60],
        [65, 70, 75, 80]
                        ])

print("Second and Third row\n", array2d[1:3])
print("First two columns",array2d[:,:2] )
print("Slice the submatrix [[30, 35], [50, 55]]\n", array2d[1:3, 1:3])
print("All the element from the last row in the reverse order\n",array2d[-1, ::-1] )

Second and Third row
 [[25 30 35 40]
 [45 50 55 60]]
First two columns [[ 5 10]
 [25 30]
 [45 50]
 [65 70]]
Slice the submatrix [[30, 35], [50, 55]]
 [[30 35]
 [50 55]]
All the element from the last row in the reverse order
 [80 75 70 65]


In [ ]:
# Create a 3D array
# Extract the first block ([[1,2,3],[4,5,6]]).
# Slice out all blocks but only the first row of each.
# Get all blocks, only the last column (3,6,9,12,15,18).
# Extract the middle block ([[7,8,9],[10,11,12]]).

array3d = np.array([
                    [[1, 2, 3], 
                     [4, 5, 6]],
                    [[7, 8, 9], 
                     [10, 11, 12]],
                    [[13, 14, 15], 
                     [16, 17, 18]]
                                    ])

print("First block\n", array3d[0])
print("First row of each block", array3d[:, 0])
print("Last Column\n", array3d[:, :, -1])
print("Middle Block\n", array3d[1, :])





First block
 [[1 2 3]
 [4 5 6]]
First row of each block [[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]
Last Column
 [[ 3  6]
 [ 9 12]
 [15 18]]
Middle Block
 [[ 7  8  9]
 [10 11 12]]
