Datatype Practice Questions

In [2]:
# Create a NumPy array a with elements [10, 20, 30, 40]. Check its data type.
import numpy as np

array = np.array([10, 20, 30, 40])
check_type = array.dtype
print("Datatype of Array is: ", check_type)

Datatype of Array is:  int64


In [4]:
# Create a NumPy array b with elements [1.5, 2.7, 3.8]. Convert it to integer type.

b = np.array([1.5, 2.7, 3.8])
b_to_int = b.astype(int)
print("Datatype of Array", b_to_int.dtype)

Datatype of Array int64


In [3]:
import numpy as np
# Create a NumPy array c with elements [True, False, True]. Convert it to float.

c = np.array([True, False, True])
c_to_float = c.astype(float)
print("Original Array: ", c)
print("Array after changing datatype: ", c_to_float)
print("Datatype of Array is: ", c_to_float.dtype)


Original Array:  [ True False  True]
Array after changing datatype:  [1. 0. 1.]
Datatype of Array is:  float64


In [5]:
# Create an array d with elements [1, 2, '3', 4]. Check its data type.
d = np.array([1, 2, '3', 4])
datatype_check = d.dtype
print("Datatype of the array is: ", datatype_check)

Datatype of the array is:  <U21


In [6]:
# Create an array e of strings ['1', '2', '3'] and convert it to integers.
e = np.array(['1', '2', '3'])
datatype_check = e.dtype
print("Datatype of the array is: ", datatype_check)

Datatype of the array is:  <U1


In [9]:
# Create a NumPy array of integers [10, 20, 30] and convert it to Unicode string type.
integers = np.array([10, 20 , 30])
integers_to_unicode = integers.astype(str)
print("Integers array ot unicode string", integers_to_unicode)
print("Datatype of the array is: ", integers_to_unicode.dtype)

Integers array ot unicode string ['10' '20' '30']
Datatype of the array is:  <U21


In [ ]:
# Create a 2D array f = [[1, 2], [3, 4]] and convert it to float type.
f = np.array([[1, 2], [3, 4]])
f_to_float = f.astype(float)
print("Original Array", f)
print("Array after changing the datatype", f_to_float)
print("Datatype of the array", f_to_float.dtype)

Original Array [[1 2]
 [3 4]]
Array after changing the datatype [[1. 2.]
 [3. 4.]]
Datatype of the array float64


In [ ]:
# Create an object array with elements [10, 'hello', 3.5]. Check its type.
arr = np.array([10, 'hello', 3.5])
print("Original array", arr,"\nDatatype of original array: ", arr.dtype)

arr_to_object = arr.astype(object)
print("Array after changing datatype", arr_to_object,"\nDatatype of modified array: ", arr_to_object.dtype)

Original array ['10' 'hello' '3.5'] 
Datatype of original array:  <U32
Array after changing datatype ['10' 'hello' '3.5'] 
Datatype of modified array:  object


In [18]:
# Convert an array g = [1.2, 3.5, 5.7] to boolean type.
g = np.array([1.2, 3.5, 5.7])
g_to_bool = g.astype(bool)
print("Original array: ", g,"\nDatatype of original array: ", g.dtype)
print("Array after changing datatype to boolean: ", g_to_bool, "\nDatatype of modified array: ", g_to_bool.dtype)

Original array:  [1.2 3.5 5.7] 
Datatype of original array:  float64
Array after changing datatype to boolean:  [ True  True  True] 
Datatype of modified array:  bool


In [21]:
# Create an array h = [65, 66, 67] and convert it to character (U1) type (Unicode character).
h = np.array([65, 66, 67])
h_to_U1 = h.astype(str)
print("Datatype of original array: ", h.dtype)
print("Datatype of modified array: ", h_to_U1.dtype)

Datatype of original array:  int64
Datatype of modified array:  <U21


Reshape Practice Questions

In [26]:
# Create an array a = [1, 2, 3, 4, 5, 6] and reshape it into a 2×3 array.

a = np.array([1, 2, 3, 4, 5, 6])
reshaped_a = a.reshape(2, 3)
print("Original Array: ", a)
print("\nReshaped Array: \n", reshaped_a)

Original Array:  [1 2 3 4 5 6]

Reshaped Array: 
 [[1 2 3]
 [4 5 6]]


In [27]:
# Create an array b = [1, 2, 3, 4, 5, 6, 7, 8] and reshape it into a 4×2 array.
b = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reshaped_b = b.reshape(4, 2)
print("Original Array: ", b)
print("\nReshaped Array: \n", reshaped_b)

Original Array:  [1 2 3 4 5 6 7 8]

Reshaped Array: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [29]:
# Reshape the array c = np.arange(12) into a 3×4 array.
c = np.arange(12)
print("Original Array: ", c)
reshaped_c = c.reshape(3, 4)
print("\nReshaped Array: \n", reshaped_c)

Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [31]:
# Reshape d = np.arange(8) into a 2×2×2 3D array
d = np.arange(8)
print("Original Array: ", d)
reshaped_d = d.reshape(2, 2, 2)
print("\nReshaped Array: \n", reshaped_d)

Original Array:  [0 1 2 3 4 5 6 7]

Reshaped Array: 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [42]:
# Use -1 to automatically infer one dimension: reshape e = np.arange(12) into a 3×? array.
e = np.arange(12)
print("Original Array: ", e)
reshaped_e = e.reshape(3, -1)
print("\nReshaped array: \n", reshaped_e)



Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [34]:
# Flatten a 2D array f = [[1, 2, 3], [4, 5, 6]] into 1D
f = np.array([[1, 2, 3], [4, 5, 6]])
reshaped_f = f.reshape(-1)
print("Original Array: \n", f)
print("\nReshaped Array: ", reshaped_f)

Original Array: 
 [[1 2 3]
 [4 5 6]]

Reshaped Array:  [1 2 3 4 5 6]


In [38]:
# Reshape a 3D array g = np.arange(24).reshape(2, 3, 4) into 4×6.
g  = np.arange(24).reshape(2, 3, 4)
print("Original Array: \n", g)
reshaped_g = g.reshape(4, 6)
print("\nReshaped Array: \n", reshaped_g)

Original Array: 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Reshaped Array: 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [40]:
# Given h = np.array([1, 2, 3, 4, 5, 6]), try reshaping into 4×2 (should it work? Why/why not?)
h = np.array([1, 2, 3, 4, 5, 6])
print("Original Array: ", h)
reshaped_h = h.reshape(4, 2)
print("\nReshaped Array: \n", reshaped_h)

Original Array:  [1 2 3 4 5 6]


ValueError: cannot reshape array of size 6 into shape (4,2)