Student Marks Analyzer – Mini Project

Instructions: Use NumPy to solve the following tasks.

Problem Statement:

You are asked to analyze the marks of 100 students in 5 subjects. The marks should be randomly generated (between 0 and 100).

Tasks:

Data Generation

Create a NumPy array of shape (100, 5) with random integers between 0 and 100.
Each row represents a student, and each column represents a subject.

Average per Subject

Find the average marks for each subject.

Top Student

Calculate the total marks for each student.
Find the student who scored the highest total marks.

Pass/Fail Count

A student is considered "Pass" only if they scored at least 40 marks in every subject.
Count how many students passed and how many failed.

Hint:

Use np.random.randint() for generating marks.
Try np.mean(), np.sum(), np.argmax(), and logical conditions with NumPy.

In [1]:
import numpy as np
marks = np.random.randint(0, 100, size=(100, 5))
print(marks)

[[29 55 55 68 75]
 [ 9 21 38 58 25]
 [63 91 82 67 69]
 [ 5 95 46 17 52]
 [26 85 18 70 72]
 [86 47 26 95 60]
 [64 78 97 18 84]
 [39 42 59 65 44]
 [24 97  7 63 42]
 [43 22 69 94 51]
 [70 39 35 62  4]
 [11 66 40 47 61]
 [34 65 27 24  5]
 [67 35 19 80 75]
 [48 20 21 29 94]
 [82 76 91 29 88]
 [98 96 87 15 22]
 [57 92  6 75  0]
 [15 57 39 12 28]
 [40 38 18 61 13]
 [87 56 17 46 46]
 [47 71 91 95 14]
 [93 24 36 71 50]
 [94 77 45 14 17]
 [79 18 30 95 72]
 [54 22 51 72 14]
 [83 38 99 76 51]
 [21 87 22  9 45]
 [71 47 74  3  1]
 [98 62 82  5 31]
 [21 10  9 75 25]
 [50 63 51 29 25]
 [25 31 63 99 32]
 [30 13 90 11 11]
 [13 34 47 49 21]
 [64 49 99  8  1]
 [93 51 11 54  1]
 [70 21 47 13 15]
 [13 21  2 69 86]
 [30 52 93  6 14]
 [18 86 30  9 32]
 [26 80  9  5 16]
 [21 81 31 79 59]
 [76 29 72 16 26]
 [95 85 53 77 56]
 [65 22 33 33 89]
 [85 81 37 36 85]
 [28 20 35 36 49]
 [91 73 53 10 67]
 [ 8 73 79 11 87]
 [27 95  3 93  4]
 [14 59 99 83 79]
 [67 63 29 43 99]
 [76 24 31 54  8]
 [ 2  1 10 69 59]
 [63 85 91

# Average per subject

In [41]:
avg_marks_per_subject = np.mean(marks, axis=0)
print("Average marks per subject: ", avg_marks_per_subject)

Average marks per subject:  [49.1  48.17 46.63 49.11 48.52]


# Top Student

#### Calculate the total marks for each student.
#### Find the student who scored the highest total marks.



In [42]:
total_marks_of_each_student = np.sum(marks, axis=1)
print("Total marks of ach student: ", total_marks_of_each_student)

highest_total_marks = np.argmax(total_marks_of_each_student, )
print("Highest total marks of a student: ", total_marks_of_each_student[highest_total_marks])

Total marks of ach student:  [219 397 200 255 345 212 249 160 254 184 209 232 188 147 242 275 195 250
 294 218 111 270 247 257 217 257 172 249 274 265 252 270 259 295 379 190
 145 169 251 233 295 288 268 337 363 221 225 233 202 297 299 254 302 183
  94 200 252 273 191 177 234 190 274 263 104 294 174 191 258 235 349 171
 183 173 289 360 245 286 424 246 263 251 321 142 382 201 197 167 381 248
 115 253 270 236 169 248 177 201 257 290]
Highest total marks of a student:  424


## Pass/Fail Count

#### A student is considered "Pass" only if they scored at least 40 marks in every subject.
#### Count how many students passed and how many failed.


In [43]:
passed = np.all(marks > 40, axis=1)

count_passed = np.sum(passed)
print("Total number of students passed: ", count_passed)

count_failed = len(marks) - count_passed
print("Total number of studetns failed: ", count_failed)

Total number of students passed:  7
Total number of studetns failed:  93
