####  1. Create a 1D NumPy array with values from 10 to 50 with step size 5.

In [2]:
import numpy as np
arr1 = np.arange(10, 50, 5)
print("1D Array: ", arr1)

1D Array:  [10 15 20 25 30 35 40 45]


#### 2. Generate a 2D array of shape (3,4) filled with random integers between 1 and 100.


In [6]:
arr2 = np.random.randint(1, 100, size=(3, 4))
print("2D Array: \n", arr2)

2D Array: 
 [[34 64 13  9]
 [30 50 13  8]
 [65 53 52 30]]


#### 3. Extract all even numbers from the array [12, 45, 67, 23, 89, 10, 56].

In [10]:
arr3 = np.array([12, 45, 67, 23, 89, 10, 56])
even_nums = np.where(arr3 % 2 == 0)
print("Even Numbers: ", arr3[even_nums])

Even Numbers:  [12 10 56]


#### 4. Slice out the last 2 rows and first 2 columns from a (4×4) array of numbers 1–16.

In [14]:
arr4 = np.random.randint(1, 16,  size=(4, 4))
print(arr4)
print(arr4[-2:, -2:])


[[ 1 12 11 13]
 [15 11  1 13]
 [ 4  5  1  2]
 [ 8  4  5 12]]
[[ 1  2]
 [ 5 12]]


#### 5. Create a (5×5) identity matrix and multiply it with a vector [1,2,3,4,5].

In [22]:
arr5 = np.identity(5, dtype=int)
print("Mutliplication of matrix with vetor: \n", arr5 * [1, 2, 3, 4, 5])

Mutliplication of matrix with vetor: 
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#### 6. Generate 10 evenly spaced numbers between 0 and 2π and compute their sine value

In [166]:
arr6 = np.linspace(2, 2*np.pi, 10)
print(arr6)

[2.         2.47590948 2.95181896 3.42772844 3.90363791 4.37954739
 4.85545687 5.33136635 5.80727583 6.28318531]


#### 7. Reshape a 1D array of numbers 1–12 into a 3×4 matrix

In [64]:
arr7 = np.arange(1, 13)
print("Original Array: ", arr7)
reshaped_arr7 = arr7.reshape((3, 4))
print("Reshaped Array: \n", reshaped_arr7)

Original Array:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### 8. Stack two arrays [1,2,3] and [4,5,6] vertically and horizontally.


In [69]:
arr8 = np.array([1, 2, 3])
arr8a = np.array([4, 5, 6])

print("Horizontal stack: ", "Array 8: \n", np.hstack(arr8))
print("Horizontal stack: ", "Array 8a: \n", np.hstack(arr8a))
print("Vertical stack: ", "Array 8: \n", np.vstack(arr8))
print("Vertical stack: ", "Array 8a: \n", np.vstack(arr8a))



Horizontal stack:  Array 8: 
 [1 2 3]
Horizontal stack:  Array 8a: 
 [4 5 6]
Vertical stack:  Array 8: 
 [[1]
 [2]
 [3]]
Vertical stack:  Array 8a: 
 [[4]
 [5]
 [6]]


#### 9. Create a boolean mask for numbers greater than 25 in [12, 34, 56, 78, 90, 11, 45, 67].


In [72]:
arr9 = np.array([12, 34, 56, 78, 90, 11, 45, 67])
mask = arr9 > 25
print("Number greater than 25: ", arr9[mask])
print("Mask for the number greater than 25: ", mask)

Number greater than 25:  [34 56 78 90 45 67]
Mask for the number greater than 25:  [False  True  True  True  True False  True  True]


#### 10. Sort the array [23, 1, 56, 3, 78, 12] in ascending and descending order.


In [79]:
arr10 = np.array([23, 1, 56, 3, 78, 12])

print("Sorting in Ascending order: ", np.sort(arr10))
print("Sorting in Descending order: ", np.sort(arr10)[::-1])

Sorting in Ascending order:  [ 1  3 12 23 56 78]
Sorting in Descending order:  [78 56 23 12  3  1]


#### 11. Find the maximum value and its index in a random (3×3) array.

In [ ]:
arr11 = np.random.rand(3, 3)
print("Array: ", arr11)
print("Maximum value in random 3 X 3 array: ", arr11.max())

Array:  [[0.37176901 0.67688987 0.00385194]
 [0.48826025 0.2703737  0.30028124]
 [0.41631305 0.01488449 0.84835603]]
Maximum value in random 3 X 3 array:  0.8483560294372428


#### 12. Generate a (4×4) array and replace all elements greater than 10 with 0.

In [132]:
arr12 = np.random.randint(0, 20, size=(4, 4))
print("Original Array: ", arr12)

replace_elements_with_0 = np.where(arr12 > 10, 0, arr12)
print("After replacing elements with 0", replace_elements_with_0)

Original Array:  [[ 4 19 18 10]
 [ 5 15  6 19]
 [16 16  3  0]
 [ 8  6  0 17]]
After replacing elements with 0 [[ 4  0  0 10]
 [ 5  0  6  0]
 [ 0  0  3  0]
 [ 8  6  0  0]]


#### 13. Create a 3D array of shape (2,3,4). Access the second 2D matrix.

In [163]:
arr13 = np.random.randint(0, 30, size=(2, 3, 4))
print("Orginal Matrix: ", arr13)
print("Second 2D Matrix: ", arr13[1])

Orginal Matrix:  [[[ 2 17 27 23]
  [21 24 23  0]
  [26 14 17 20]]

 [[12 11  2  3]
  [22 17  8 20]
  [25 26  1 23]]]
Second 2D Matrix:  [[12 11  2  3]
 [22 17  8 20]
 [25 26  1 23]]


#### 14. Use broadcasting to add a (3×1) column vector [1,2,3] to a (3×3) matrix of ones.

In [167]:
arr = np.arange(1, 10)
print(arr)

[1 2 3 4 5 6 7 8 9]


140706171528392 140706171528392


#### 15. Compute element-wise multiplication and matrix multiplication of
#### A = [[1,2],[3,4]], B = [[5,6],[7,8]]

In [138]:
arr15 = np.array([[1, 2],[3, 4]])
arr15a = np.array([[5, 6], [7, 8]])

print("Element wise Multliplication of matrix: \n", arr15 * arr15a)

Element wise Multliplication of matrix: 
 [[ 5 12]
 [21 32]]


#### 16. Find the mean, median, and standard deviation of [10,20,30,40,50,60,70].

In [143]:
arr16 = np.array([10, 20, 30, 40, 50, 60, 70])

mean_arr16 = np.mean(arr16)
print("Mean: ", mean_arr16)

median_arr16 = np.median(arr16)
print("Median: ", median_arr16)

std_deviation_arr16 = np.std(arr16)
print("Standard Deviation: ", std_deviation_arr16)

Mean:  40.0
Median:  40.0
Standard Deviation:  20.0


#### 17. Use np.where to find indices of numbers divisible by 3 in [12, 45, 67, 23, 89, 10, 56].


In [148]:
arr17 = np.array([12, 45, 67, 23, 89, 10, 56])

indices = np.where(arr17 % 3 == 0)
print("Indices of number divisible by 3: ", indices)
print("Numbers that are divisible by 3: ", arr17[indices])

Indices of number divisible by 3:  (array([0, 1]),)
Numbers that are divisible by 3:  [12 45]


#### 18. Create an array of complex numbers and extract their real and imaginary parts.

#### 19. Generate a random array of shape (100,) and count how many numbers are greater than 0.5.

In [161]:
arr19 = np.random.rand(100, )
print("Orginal Array: \n", arr19)

check_condition = np.where(arr19 > 0.5)
print("\nNumbers that are greater than 0.5: \n", arr19[check_condition])

Orginal Array: 
 [0.55701069 0.95055666 0.26589205 0.9608881  0.73803133 0.63622648
 0.01014255 0.00437965 0.08392767 0.55008646 0.58951462 0.75472316
 0.34817199 0.54349453 0.80085901 0.76613416 0.80452262 0.79967806
 0.73997561 0.35531086 0.46864687 0.48618588 0.31934099 0.50600277
 0.19445043 0.89790351 0.15482075 0.51039788 0.02141238 0.32235922
 0.76738871 0.38449745 0.69959553 0.06245696 0.99690143 0.40324771
 0.78181615 0.91343839 0.67562493 0.75131417 0.22607974 0.78811768
 0.23226893 0.73151751 0.56064075 0.80468513 0.36628155 0.11063178
 0.78808291 0.59801538 0.52062078 0.27751661 0.77937334 0.91082825
 0.65994981 0.15744001 0.80495541 0.05122557 0.38295485 0.79144968
 0.41759556 0.40016596 0.13869464 0.33263116 0.8499076  0.09094183
 0.24282109 0.35492324 0.92054905 0.70959239 0.84250508 0.90285179
 0.63196492 0.98365397 0.39163051 0.54150215 0.87156635 0.74355836
 0.77161983 0.77635066 0.37287158 0.08607101 0.71976622 0.41083761
 0.83070382 0.96358974 0.14085735 0.29713174 

In [ ]:
ls = [4,6,0,-1,2,4,1,3]
index = len(ls)
for i in range(index):
    for j in range(i + 1, index):
        if ls[i] > ls[j]:
            ls[i], ls[j] = ls[j], ls[i]

result_list = []

for i in ls:
    if i not in result_list:
        result_list.append(i)
print(result_list)



-1
0
1
2
3
4
4
6
[-1, 0, 1, 2, 3, 4, 6]


a
b
c
a
b
c
d
e
a
f
g
