In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4])
for i in a:
    print(i)

1
2
3
4
[[1]
 [2]
 [3]
 [4]]


In [9]:
b = np.array([[1, 2, 3], 
              [4, 5, 6]])
for i in b:
    for j in i:
        print(j)

1
2
3
4
5
6


np.nditer() method 
used to interate through the multidimensional array

In [11]:
c = np.array([[1, 2, 3], 
              [4, 5, 6]])

for i in np.nditer(c):
    print(i)

1
2
3
4
5
6


In [4]:
import numpy as np
d = np.array([[1, 2, 3],
             [4, 5, 6]])
for i, j in np.ndenumerate(d):
    print(i, j)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [14]:
e = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]]])
for i, j in np.ndenumerate(e):
    print(i,j)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 2, 0) 7
(0, 2, 1) 8
(0, 2, 2) 9


Searching

In [14]:
f = np.array([1, 2, 3, 4, 5, 6, 7])
g = np.where(f > 4, f*2, f)
print(g)

[ 1  2  3  4 10 12 14]


In [27]:
#find even or odd
h = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
i = np.where(h % 2 == 0)
print(h[i])

[ 2  4  6  8 10]


Sorting

In [ ]:
j = np.array([4, 5, 3, 7, 9, 10, 56, 67, 87])
k = np.sort(j)
print("Sorting in ascending order: ", k)

[ 3  4  5  7  9 10 56 67 87]


In [34]:
l = np.array([4, 5, 3, 7, 9, 10, 56, 67, 87])
m = np.sort(l)[::-1]
print("Sorting in descending order: ", m)

Sorting in descending order:  [87 67 56 10  9  7  5  4  3]


Searchsorted

Searchsorted method is used to perform binary search in th array and return the index where specified value would be inserted in order to maintain the search order

In [52]:
n = np.array([1, 3, 8, 5, 7, 9])
o = np.searchsorted(n, 6)
print("Index where 6 should be inserted to maintain order is: ", o)

Index where 6 should be inserted to maintain order is:  4


In [2]:
import numpy as np
p = np.array([[1, 3, 5], 
              [7, 9, 11]])
val = 8
q = np.searchsorted(p, val)       
print("Index where 8 should be inserted to maintain order is: ", q)


ValueError: object too deep for desired array