NumPy Datatypes

In [18]:
import numpy as np
a = np.array([1, 2, 3, 4])
print(f"Datatype of a = {a}: ", a.dtype)

n = np.array([1, 2, 3, 4, 5.9])
print(f"Datatype of n = {n}: ", n.dtype)

b = np.array(["a", "b", "c", "d"])
print(f"Dataype of b = {b}: ", b.dtype)

c = np.array([1, 1.2, "Hello"])
print(f"Datatype of c = {c}: ", c.dtype)

d = np.array([[1, 2], (1, 2), {"a" : 1}], dtype = object)
print(f"Datatype of d = {d}",d.dtype)

Datatype of a = [1 2 3 4]:  int64
Datatype of n = [1.  2.  3.  4.  5.9]:  float64
Dataype of b = ['a' 'b' 'c' 'd']:  <U1
Datatype of c = ['1' '1.2' 'Hello']:  <U32
Datatype of d = [list([1, 2]) (1, 2) {'a': 1}] object


In [22]:
a = np.array([1.2, 2.3, 3.4, 4.5], dtype= int )
print(a)

[1 2 3 4]


In [23]:
a = np.array([1, 0, 3], dtype= bool)
print(a)

[ True False  True]


In [25]:
a = np.array([1, 4, 6, 7], dtype= float)
print(a)

[1. 4. 6. 7.]


In [28]:
a = np.array([1, 4, 6, 8, 3], dtype= str)
print(a)
print(a.dtype)

['1' '4' '6' '8' '3']
<U1


In [31]:
a = np.array([1.2, 2.3, 3.4, 4.5])
x = a.astype(int)
print(x)
print(x.dtype)

[1 2 3 4]
int64


In [34]:
a = np.arange(28)
print(a)
a = a.reshape(4, 7)
print(a)
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]
2


In [38]:
a = np.arange(10)
print(a)
a = a.reshape(2, 5, 1)
print(a.ndim)

[0 1 2 3 4 5 6 7 8 9]
3


In [40]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a,"\n")
a = a.reshape(3, 3, 1)
print(a)
print(a.ndim)



[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
3


In [44]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print("2d array\n", a)
a = a.reshape(6)
print("2d to 1d\n", a)


2d array
 [[1 2 3]
 [4 5 6]]
2d to 1d
 [1 2 3 4 5 6]


In [42]:
a = np.array([[[1, 2],
               [3, 4],
               [5, 6]]])
print("3d\n",a)
a = a.reshape(6)
print("3d to 1d\n", a)

3d
 [[[1 2]
  [3 4]
  [5 6]]]
3d to 1d
 [1 2 3 4 5 6]


In [46]:
array = np.array([[[1, 2],
                   [3, 4], 
                   [4, 5]]])
print("3d array\n", array)
array = array.reshape(-1)
print("3d to 1d array\n", array)

3d array
 [[[1 2]
  [3 4]
  [4 5]]]
3d to 1d array
 [1 2 3 4 4 5]
